volumes:
  mongodb_data:

services:
  mongodb:
    image: mongo:7.0
    container_name: goals-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: goals-backend
    environment:
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      MONGO_DATABASE: ${MONGO_DATABASE}
    ports:
      - "80:80"
    depends_on:
      - mongodb
    volumes:
      - ./backend/logs:/app/logs  # Persist logs on host

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost}
    container_name: goals-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
